version: '3'

services: 

  server: 
    build: ./api/
    expose: 
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      API_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./api/src:/srv/app/api/src
    command: npm run start

  
  client: 
    build: ./client
    environment: 
      - REACT_APP_PORT:{REACT_APP_PORT}
    expose: 
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/client/src
      - ./client/public:/srv/app/client/public
    
    links: 
      - server
    
    command: npm run start

    
    